[build]
target = ["riscv32ima-unknown-none-elf"]

[target.riscv32ima-unknown-none-elf]
rustflags = [
    "-C", "relocation-model=pic", 
    "-C", "link-arg=-no-pie"]

[unstable]
build-std = ["core", "alloc"]
